2025-04-29 15:05:07,236 - DEBUG - Subprocess stdout: {"status": "success", "message": "Semua 1 file berhasil diproses!", "last_row": 4}

2025-04-29 15:05:07,236 - DEBUG - Subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp2.xlsx']
File 1 found: D:\Internship\automation\automation\uploads\lkp2.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 32, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 43, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 68, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 87, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp2.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 198, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 2 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 198, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 3 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 217, in process_files
    logging.info(f"\u2705 File {file_path} berhasil diproses!")
Message: '\u2705 File D:\\Internship\\automation\\automation\\uploads\\lkp2.xlsx berhasil diproses!'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 230, in process_files
    logging.info("\u2705 Semua file telah diproses!")
Message: '\u2705 Semua file telah diproses!'
Arguments: ()

2025-04-29 15:05:07,236 - DEBUG - Subprocess returncode: 0
2025-04-29 15:05:07,248 - INFO - Successfully processed 1 files
2025-04-29 15:06:00,186 - DEBUG - Subprocess stdout: {"status": "error", "message": "Terdeteksi berhenti pada baris 3", "last_row": 3}

2025-04-29 15:06:00,186 - DEBUG - Subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx']
File 1 found: D:\Internship\automation\automation\uploads\lkp23.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 32, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 43, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 68, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 87, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 198, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 2 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 140, in process_files
    link_tambah_siswa = driver.find_element(
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 898, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: MicrosoftEdge=135.0.3179.98)
Stacktrace:
	GetHandleVerifier [0x00007FF6D7AF7A55+24981]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A4AC60+444240]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6D7D7E0EA+2011274]
	(No symbol) [0x00007FF6D77FC2B5]
	(No symbol) [0x00007FF6D788EBF0]
	(No symbol) [0x00007FF6D78A61EA]
	(No symbol) [0x00007FF6D7888E03]
	(No symbol) [0x00007FF6D785D686]
	(No symbol) [0x00007FF6D785CB92]
	(No symbol) [0x00007FF6D785D4B3]
	(No symbol) [0x00007FF6D795900D]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D7966943+41539]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D795FC79+13689]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6D7BDA04A+290794]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A57D31+497697]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50BB4+468644]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50D03+468979]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A42E16+411910]
	BaseThreadInitThunk [0x00007FF800A5259D+29]
	RtlUserThreadStart [0x00007FF80186AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 34: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 200, in process_files
    logging.error(f"\u274c Browser ditutup pada baris {i}: {e}")
Message: '\u274c Browser ditutup pada baris 3: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: MicrosoftEdge=135.0.3179.98)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7AF7A55+24981]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A4AC60+444240]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6D7D7E0EA+2011274]\n\t(No symbol) [0x00007FF6D77FC2B5]\n\t(No symbol) [0x00007FF6D788EBF0]\n\t(No symbol) [0x00007FF6D78A61EA]\n\t(No symbol) [0x00007FF6D7888E03]\n\t(No symbol) [0x00007FF6D785D686]\n\t(No symbol) [0x00007FF6D785CB92]\n\t(No symbol) [0x00007FF6D785D4B3]\n\t(No symbol) [0x00007FF6D795900D]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D7966943+41539]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D795FC79+13689]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6D7BDA04A+290794]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A57D31+497697]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50BB4+468644]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50D03+468979]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A42E16+411910]\n\tBaseThreadInitThunk [0x00007FF800A5259D+29]\n\tRtlUserThreadStart [0x00007FF80186AF38+40]\n'
Arguments: ()

2025-04-29 15:06:00,186 - DEBUG - Subprocess returncode: 0
2025-04-29 15:06:00,186 - WARNING - Process failed at row 3: Terdeteksi berhenti pada baris 3
2025-04-29 15:08:09,680 - INFO - D:\Internship\automation\automation\automation\views.py changed, reloading.
2025-04-29 15:09:50,854 - DEBUG - Subprocess stdout: {"status": "error", "message": "Terdeteksi berhenti pada baris 7", "last_row": 7}

2025-04-29 15:09:50,854 - DEBUG - Subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx']
File 1 found: D:\Internship\automation\automation\uploads\lkp23.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 32, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 43, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 68, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 87, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 198, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 2 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 198, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 3 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 198, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 4 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 198, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 5 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 198, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 6 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 148, in process_files
    driver.execute_script("arguments[0].click();", link_tambah_siswa)
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 528, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: MicrosoftEdge=135.0.3179.98)
Stacktrace:
	GetHandleVerifier [0x00007FF6D7AF7A55+24981]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A4AC60+444240]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6D7D7E0EA+2011274]
	(No symbol) [0x00007FF6D780B880]
	(No symbol) [0x00007FF6D782A24A]
	(No symbol) [0x00007FF6D788ED66]
	(No symbol) [0x00007FF6D78A61EA]
	(No symbol) [0x00007FF6D7888E03]
	(No symbol) [0x00007FF6D785D686]
	(No symbol) [0x00007FF6D785CB92]
	(No symbol) [0x00007FF6D785D4B3]
	(No symbol) [0x00007FF6D795900D]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D7966943+41539]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D795FC79+13689]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6D7BDA04A+290794]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A57D31+497697]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50BB4+468644]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50D03+468979]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A42E16+411910]
	BaseThreadInitThunk [0x00007FF800A5259D+29]
	RtlUserThreadStart [0x00007FF80186AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 34: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 200, in process_files
    logging.error(f"\u274c Browser ditutup pada baris {i}: {e}")
Message: '\u274c Browser ditutup pada baris 7: Message: invalid session id: session deleted as the browser has closed the connection\nfrom disconnected: not connected to DevTools\n  (Session info: MicrosoftEdge=135.0.3179.98)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7AF7A55+24981]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A4AC60+444240]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6D7D7E0EA+2011274]\n\t(No symbol) [0x00007FF6D780B880]\n\t(No symbol) [0x00007FF6D782A24A]\n\t(No symbol) [0x00007FF6D788ED66]\n\t(No symbol) [0x00007FF6D78A61EA]\n\t(No symbol) [0x00007FF6D7888E03]\n\t(No symbol) [0x00007FF6D785D686]\n\t(No symbol) [0x00007FF6D785CB92]\n\t(No symbol) [0x00007FF6D785D4B3]\n\t(No symbol) [0x00007FF6D795900D]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D7966943+41539]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D795FC79+13689]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6D7BDA04A+290794]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A57D31+497697]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50BB4+468644]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50D03+468979]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A42E16+411910]\n\tBaseThreadInitThunk [0x00007FF800A5259D+29]\n\tRtlUserThreadStart [0x00007FF80186AF38+40]\n'
Arguments: ()

2025-04-29 15:09:50,854 - DEBUG - Subprocess returncode: 0
2025-04-29 15:09:50,868 - WARNING - Process failed at row 7: Terdeteksi berhenti pada baris 7
2025-04-29 15:12:47,161 - DEBUG - Subprocess stdout: {"status": "error", "message": "Error tidak terduga pada baris 7: 'NoneType' object has no attribute 'send_keys'", "last_row": 7}

2025-04-29 15:12:47,161 - DEBUG - Subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx']
File 1 found: D:\Internship\automation\automation\uploads\lkp23.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 32, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 43, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 68, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 87, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 198, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 2 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 198, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 3 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 198, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 4 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 198, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 5 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 198, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 6 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 184, in process_files
    driver.find_element(By.NAME, "asal_domisili").send_keys(Asal)
AttributeError: 'NoneType' object has no attribute 'send_keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 34: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 210, in process_files
    logging.error(f"\u274c Error tidak terduga pada baris {i}: {e}")
Message: "\u274c Error tidak terduga pada baris 7: 'NoneType' object has no attribute 'send_keys'"
Arguments: ()

2025-04-29 15:12:47,161 - DEBUG - Subprocess returncode: 0
2025-04-29 15:12:47,177 - WARNING - Process failed at row 7: Error tidak terduga pada baris 7: 'NoneType' object has no attribute 'send_keys'
2025-04-29 15:14:10,712 - DEBUG - Subprocess stdout: {"status": "error", "message": "Error tidak terduga pada baris 2: 'NoneType' object has no attribute 'send_keys'", "last_row": 2}

2025-04-29 15:14:10,712 - DEBUG - Subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx']
File 1 found: D:\Internship\automation\automation\uploads\lkp23.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 32, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 43, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 68, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 87, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 182, in process_files
    driver.find_element(By.NAME, "tempat_lahir_ayah").send_keys(Tempat_Lahir_Ortu)
AttributeError: 'NoneType' object has no attribute 'send_keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 34: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 273, in <module>
    result = process_files(sys.argv[1:])
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 210, in process_files
    logging.error(f"\u274c Error tidak terduga pada baris {i}: {e}")
Message: "\u274c Error tidak terduga pada baris 2: 'NoneType' object has no attribute 'send_keys'"
Arguments: ()

2025-04-29 15:14:10,712 - DEBUG - Subprocess returncode: 0
2025-04-29 15:14:10,731 - WARNING - Process failed at row 2: Error tidak terduga pada baris 2: 'NoneType' object has no attribute 'send_keys'
2025-04-29 15:22:19,695 - INFO - D:\Internship\automation\automation\automation\views.py changed, reloading.
2025-04-29 15:24:14,320 - INFO - D:\Internship\automation\automation\pkl\urls.py changed, reloading.
2025-04-29 15:24:57,245 - WARNING - Not Found: /favicon.ico
2025-04-29 15:39:04,008 - ERROR - File not found: D:\Internship\automation\automation\uploads\lkp23.xlsx
2025-04-29 15:39:16,856 - ERROR - File not found: D:\Internship\automation\automation\uploads\lkp23.xlsx
2025-04-29 15:39:36,818 - ERROR - File not found: D:\Internship\automation\automation\uploads\lkp23.xlsx
2025-04-29 15:39:56,743 - ERROR - File not found: D:\Internship\automation\automation\uploads\lkp23.xlsx
2025-04-29 15:40:21,992 - ERROR - File not found: D:\Internship\automation\automation\uploads\lkp23.xlsx
2025-04-29 15:42:58,069 - INFO - D:\Internship\automation\automation\automation\views.py changed, reloading.
2025-04-29 15:44:39,234 - INFO - D:\Internship\automation\automation\automation\models.py changed, reloading.
2025-04-29 15:44:57,795 - INFO - D:\Internship\automation\automation\automation\models.py changed, reloading.
2025-04-29 15:47:01,990 - INFO - D:\Internship\automation\automation\automation\models.py changed, reloading.
2025-04-29 15:47:22,056 - INFO - D:\Internship\automation\automation\automation\models.py changed, reloading.
2025-04-29 15:47:33,342 - INFO - D:\Internship\automation\automation\automation\models.py changed, reloading.
2025-04-29 15:47:55,569 - INFO - D:\Internship\automation\automation\automation\models.py changed, reloading.
2025-04-29 15:49:23,129 - ERROR - File not found: D:\Internship\automation\automation\uploads\lkp23.xlsx
2025-04-29 15:50:17,176 - DEBUG - Subprocess stdout: {"status": "error", "message": "Terdeteksi berhenti pada baris 3", "last_row": 3}

2025-04-29 15:50:17,176 - DEBUG - Subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx']
File 1 found: D:\Internship\automation\automation\uploads\lkp23.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 35, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 46, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 71, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 90, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 2 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 143, in process_files
    link_tambah_siswa = driver.find_element(
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 898, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: MicrosoftEdge=135.0.3179.98)
Stacktrace:
	GetHandleVerifier [0x00007FF6D7AF7A55+24981]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A4AC60+444240]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6D7D7E0EA+2011274]
	(No symbol) [0x00007FF6D77FC2B5]
	(No symbol) [0x00007FF6D788EBF0]
	(No symbol) [0x00007FF6D78A61EA]
	(No symbol) [0x00007FF6D7888E03]
	(No symbol) [0x00007FF6D785D686]
	(No symbol) [0x00007FF6D785CB92]
	(No symbol) [0x00007FF6D785D4B3]
	(No symbol) [0x00007FF6D795900D]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D7966943+41539]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D795FC79+13689]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6D7BDA04A+290794]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A57D31+497697]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50BB4+468644]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50D03+468979]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A42E16+411910]
	BaseThreadInitThunk [0x00007FF800A5259D+29]
	RtlUserThreadStart [0x00007FF80186AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 34: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 203, in process_files
    logging.error(f"\u274c Browser ditutup pada baris {i}: {e}")
Message: '\u274c Browser ditutup pada baris 3: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: MicrosoftEdge=135.0.3179.98)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7AF7A55+24981]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A4AC60+444240]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6D7D7E0EA+2011274]\n\t(No symbol) [0x00007FF6D77FC2B5]\n\t(No symbol) [0x00007FF6D788EBF0]\n\t(No symbol) [0x00007FF6D78A61EA]\n\t(No symbol) [0x00007FF6D7888E03]\n\t(No symbol) [0x00007FF6D785D686]\n\t(No symbol) [0x00007FF6D785CB92]\n\t(No symbol) [0x00007FF6D785D4B3]\n\t(No symbol) [0x00007FF6D795900D]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D7966943+41539]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D795FC79+13689]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6D7BDA04A+290794]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A57D31+497697]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50BB4+468644]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50D03+468979]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A42E16+411910]\n\tBaseThreadInitThunk [0x00007FF800A5259D+29]\n\tRtlUserThreadStart [0x00007FF80186AF38+40]\n'
Arguments: ()

2025-04-29 15:50:17,176 - DEBUG - Subprocess returncode: 0
2025-04-29 15:50:17,191 - WARNING - Process failed at row 3: Terdeteksi berhenti pada baris 3
2025-04-29 15:51:45,236 - DEBUG - Resume subprocess stdout: {"status": "success", "message": "Semua 1 file berhasil diproses!", "last_row": 13}

2025-04-29 15:51:45,236 - DEBUG - Resume subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx', '--resume-from', '3']
File 1 found: D:\Internship\automation\automation\uploads\lkp23.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 35, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 46, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 71, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 90, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 3 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 4 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 5 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 6 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 7 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 8 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 9 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 10 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 11 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 12 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 220, in process_files
    logging.info(f"\u2705 File {file_path} berhasil diproses!")
Message: '\u2705 File D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx berhasil diproses!'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 233, in process_files
    logging.info("\u2705 Semua file telah diproses!")
Message: '\u2705 Semua file telah diproses!'
Arguments: ()

2025-04-29 15:51:45,236 - DEBUG - Resume subprocess returncode: 0
2025-04-29 15:51:45,236 - INFO - File deleted after successful resume: D:\Internship\automation\automation\uploads\lkp23.xlsx
2025-04-29 15:51:45,236 - INFO - Successfully resumed processing for log ID 19
2025-04-29 15:53:15,440 - DEBUG - Subprocess stdout: {"status": "error", "message": "Terdeteksi berhenti pada baris 4", "last_row": 4}

2025-04-29 15:53:15,440 - DEBUG - Subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx']
File 1 found: D:\Internship\automation\automation\uploads\lkp23.xlsx
File 2 found: D:\Internship\automation\automation\uploads\lkp23.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 35, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 46, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 71, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 90, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 2 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 3 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 151, in process_files
    driver.execute_script("arguments[0].click();", link_tambah_siswa)
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 528, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: MicrosoftEdge=135.0.3179.98)
Stacktrace:
	GetHandleVerifier [0x00007FF6D7AF7A55+24981]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A4AC60+444240]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6D7D7E0EA+2011274]
	(No symbol) [0x00007FF6D780B880]
	(No symbol) [0x00007FF6D782A24A]
	(No symbol) [0x00007FF6D788ED66]
	(No symbol) [0x00007FF6D78A61EA]
	(No symbol) [0x00007FF6D7888E03]
	(No symbol) [0x00007FF6D785D686]
	(No symbol) [0x00007FF6D785CB92]
	(No symbol) [0x00007FF6D785D4B3]
	(No symbol) [0x00007FF6D795900D]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D7966943+41539]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D795FC79+13689]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6D7BDA04A+290794]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A57D31+497697]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50BB4+468644]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50D03+468979]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A42E16+411910]
	BaseThreadInitThunk [0x00007FF800A5259D+29]
	RtlUserThreadStart [0x00007FF80186AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 34: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 203, in process_files
    logging.error(f"\u274c Browser ditutup pada baris {i}: {e}")
Message: '\u274c Browser ditutup pada baris 4: Message: invalid session id: session deleted as the browser has closed the connection\nfrom disconnected: not connected to DevTools\n  (Session info: MicrosoftEdge=135.0.3179.98)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7AF7A55+24981]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A4AC60+444240]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6D7D7E0EA+2011274]\n\t(No symbol) [0x00007FF6D780B880]\n\t(No symbol) [0x00007FF6D782A24A]\n\t(No symbol) [0x00007FF6D788ED66]\n\t(No symbol) [0x00007FF6D78A61EA]\n\t(No symbol) [0x00007FF6D7888E03]\n\t(No symbol) [0x00007FF6D785D686]\n\t(No symbol) [0x00007FF6D785CB92]\n\t(No symbol) [0x00007FF6D785D4B3]\n\t(No symbol) [0x00007FF6D795900D]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D7966943+41539]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D795FC79+13689]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6D7BDA04A+290794]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A57D31+497697]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50BB4+468644]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50D03+468979]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A42E16+411910]\n\tBaseThreadInitThunk [0x00007FF800A5259D+29]\n\tRtlUserThreadStart [0x00007FF80186AF38+40]\n'
Arguments: ()

2025-04-29 15:53:15,440 - DEBUG - Subprocess returncode: 0
2025-04-29 15:53:15,440 - WARNING - Process failed at row 4: Terdeteksi berhenti pada baris 4
2025-04-29 15:54:24,189 - INFO - D:\Internship\automation\automation\automation\views.py changed, reloading.
2025-04-29 15:54:35,447 - INFO - D:\Internship\automation\automation\automation\views.py changed, reloading.
2025-04-29 15:54:39,067 - INFO - D:\Internship\automation\automation\automation\views.py changed, reloading.
2025-04-29 15:56:01,410 - DEBUG - Resume subprocess stdout: {"status": "success", "message": "Semua 1 file berhasil diproses!", "last_row": 13}

2025-04-29 15:56:01,410 - DEBUG - Resume subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx', '--resume-from', '4']
File 1 found: D:\Internship\automation\automation\uploads\lkp23.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 35, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 46, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 71, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 90, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 4 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 5 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 6 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 7 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 8 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 9 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 10 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 11 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 12 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 220, in process_files
    logging.info(f"\u2705 File {file_path} berhasil diproses!")
Message: '\u2705 File D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx berhasil diproses!'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 233, in process_files
    logging.info("\u2705 Semua file telah diproses!")
Message: '\u2705 Semua file telah diproses!'
Arguments: ()

2025-04-29 15:56:01,410 - DEBUG - Resume subprocess returncode: 0
2025-04-29 15:56:01,416 - INFO - File deleted after successful resume: D:\Internship\automation\automation\uploads\lkp23.xlsx
2025-04-29 15:56:01,416 - INFO - Successfully resumed processing for log ID 21
2025-04-29 15:56:43,231 - ERROR - File not found: D:\Internship\automation\automation\uploads\lkp23.xlsx
2025-04-29 15:59:43,834 - INFO - D:\Internship\automation\automation\automation\views.py changed, reloading.
2025-04-29 16:00:01,399 - DEBUG - Subprocess stdout: {"status": "error", "message": "File 1 not found - D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx", "last_row": 0}

2025-04-29 16:00:01,399 - DEBUG - Subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx']

2025-04-29 16:00:01,399 - DEBUG - Subprocess returncode: 1
2025-04-29 16:00:01,413 - WARNING - Process failed at row 0: File 1 not found - D:\Internship\automation\automation\uploads\lkp23.xlsx
2025-04-29 16:00:12,097 - DEBUG - Subprocess stdout: {"status": "error", "message": "File 1 not found - D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx", "last_row": 0}

2025-04-29 16:00:12,097 - DEBUG - Subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx']

2025-04-29 16:00:12,097 - DEBUG - Subprocess returncode: 1
2025-04-29 16:00:12,112 - WARNING - Process failed at row 0: File 1 not found - D:\Internship\automation\automation\uploads\lkp23.xlsx
2025-04-29 16:03:10,622 - INFO - D:\Internship\automation\automation\automation\views.py changed, reloading.
2025-04-29 16:08:06,974 - INFO - D:\Internship\automation\automation\automation\views.py changed, reloading.
2025-04-29 16:10:24,502 - DEBUG - Subprocess stdout: {"status": "error", "message": "Terdeteksi berhenti pada baris 3", "last_row": 3}

2025-04-29 16:10:24,503 - DEBUG - Subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx']
File 1 found: D:\Internship\automation\automation\uploads\lkp23.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 35, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 46, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 71, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 90, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 2 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 151, in process_files
    driver.execute_script("arguments[0].click();", link_tambah_siswa)
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 528, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: MicrosoftEdge=135.0.3179.98)
Stacktrace:
	GetHandleVerifier [0x00007FF6D7AF7A55+24981]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A4AC60+444240]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6D7D7E0EA+2011274]
	(No symbol) [0x00007FF6D780B880]
	(No symbol) [0x00007FF6D782A24A]
	(No symbol) [0x00007FF6D788ED66]
	(No symbol) [0x00007FF6D78A61EA]
	(No symbol) [0x00007FF6D7888E03]
	(No symbol) [0x00007FF6D785D686]
	(No symbol) [0x00007FF6D785CB92]
	(No symbol) [0x00007FF6D785D4B3]
	(No symbol) [0x00007FF6D795900D]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D7966943+41539]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D795FC79+13689]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6D7BDA04A+290794]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A57D31+497697]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50BB4+468644]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50D03+468979]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A42E16+411910]
	BaseThreadInitThunk [0x00007FF800A5259D+29]
	RtlUserThreadStart [0x00007FF80186AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 34: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 203, in process_files
    logging.error(f"\u274c Browser ditutup pada baris {i}: {e}")
Message: '\u274c Browser ditutup pada baris 3: Message: invalid session id: session deleted as the browser has closed the connection\nfrom disconnected: not connected to DevTools\n  (Session info: MicrosoftEdge=135.0.3179.98)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7AF7A55+24981]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A4AC60+444240]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6D7D7E0EA+2011274]\n\t(No symbol) [0x00007FF6D780B880]\n\t(No symbol) [0x00007FF6D782A24A]\n\t(No symbol) [0x00007FF6D788ED66]\n\t(No symbol) [0x00007FF6D78A61EA]\n\t(No symbol) [0x00007FF6D7888E03]\n\t(No symbol) [0x00007FF6D785D686]\n\t(No symbol) [0x00007FF6D785CB92]\n\t(No symbol) [0x00007FF6D785D4B3]\n\t(No symbol) [0x00007FF6D795900D]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D7966943+41539]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D795FC79+13689]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6D7BDA04A+290794]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A57D31+497697]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50BB4+468644]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50D03+468979]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A42E16+411910]\n\tBaseThreadInitThunk [0x00007FF800A5259D+29]\n\tRtlUserThreadStart [0x00007FF80186AF38+40]\n'
Arguments: ()

2025-04-29 16:10:24,503 - DEBUG - Subprocess returncode: 0
2025-04-29 16:10:24,510 - INFO - Retained file for resume: D:\Internship\automation\automation\uploads\lkp23.xlsx
2025-04-29 16:10:24,510 - WARNING - Process failed at row 3: Terdeteksi berhenti pada baris 3
2025-04-29 16:11:50,357 - DEBUG - Resume subprocess stdout: {"status": "success", "message": "Semua 1 file berhasil diproses!", "last_row": 13}

2025-04-29 16:11:50,358 - DEBUG - Resume subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx', '--resume-from', '3']
File 1 found: D:\Internship\automation\automation\uploads\lkp23.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 35, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 46, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 71, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 90, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 3 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 4 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 5 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 6 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 7 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 8 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 9 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 10 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 11 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 12 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 220, in process_files
    logging.info(f"\u2705 File {file_path} berhasil diproses!")
Message: '\u2705 File D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx berhasil diproses!'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 233, in process_files
    logging.info("\u2705 Semua file telah diproses!")
Message: '\u2705 Semua file telah diproses!'
Arguments: ()

2025-04-29 16:11:50,359 - DEBUG - Resume subprocess returncode: 0
2025-04-29 16:11:50,362 - INFO - File deleted after successful resume: D:\Internship\automation\automation\uploads\lkp23.xlsx
2025-04-29 16:11:50,362 - INFO - Successfully resumed processing for log ID 24
2025-04-29 16:19:45,758 - DEBUG - Subprocess stdout: {"status": "success", "message": "Semua 1 file berhasil diproses!", "last_row": 13}

2025-04-29 16:19:45,758 - DEBUG - Subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx']
File 1 found: D:\Internship\automation\automation\uploads\lkp23.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 35, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 46, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 71, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 90, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 2 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 3 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 4 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 5 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 6 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 7 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 8 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 9 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 10 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 11 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 12 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 220, in process_files
    logging.info(f"\u2705 File {file_path} berhasil diproses!")
Message: '\u2705 File D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx berhasil diproses!'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 233, in process_files
    logging.info("\u2705 Semua file telah diproses!")
Message: '\u2705 Semua file telah diproses!'
Arguments: ()

2025-04-29 16:19:45,758 - DEBUG - Subprocess returncode: 0
2025-04-29 16:19:45,772 - INFO - Successfully processed 1 files
2025-04-29 16:27:36,621 - WARNING - Not Found: /favicon.ico
2025-04-29 16:33:18,195 - DEBUG - Subprocess stdout: {"status": "error", "message": "Terdeteksi berhenti pada baris 3", "last_row": 3}

2025-04-29 16:33:18,195 - DEBUG - Subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx']
File 1 found: D:\Internship\automation\automation\uploads\lkp23.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 35, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 46, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 71, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 90, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp23.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 2 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 151, in process_files
    driver.execute_script("arguments[0].click();", link_tambah_siswa)
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 528, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: MicrosoftEdge=135.0.3179.98)
Stacktrace:
	GetHandleVerifier [0x00007FF6D7AF7A55+24981]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A4AC60+444240]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6D7D7E0EA+2011274]
	(No symbol) [0x00007FF6D780B880]
	(No symbol) [0x00007FF6D782A24A]
	(No symbol) [0x00007FF6D788ED66]
	(No symbol) [0x00007FF6D78A61EA]
	(No symbol) [0x00007FF6D7888E03]
	(No symbol) [0x00007FF6D785D686]
	(No symbol) [0x00007FF6D785CB92]
	(No symbol) [0x00007FF6D785D4B3]
	(No symbol) [0x00007FF6D795900D]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D7966943+41539]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D795FC79+13689]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6D7BDA04A+290794]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A57D31+497697]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50BB4+468644]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50D03+468979]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A42E16+411910]
	BaseThreadInitThunk [0x00007FF800A5259D+29]
	RtlUserThreadStart [0x00007FF80186AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 34: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 203, in process_files
    logging.error(f"\u274c Browser ditutup pada baris {i}: {e}")
Message: '\u274c Browser ditutup pada baris 3: Message: invalid session id: session deleted as the browser has closed the connection\nfrom disconnected: not connected to DevTools\n  (Session info: MicrosoftEdge=135.0.3179.98)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7AF7A55+24981]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A4AC60+444240]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6D7D7E0EA+2011274]\n\t(No symbol) [0x00007FF6D780B880]\n\t(No symbol) [0x00007FF6D782A24A]\n\t(No symbol) [0x00007FF6D788ED66]\n\t(No symbol) [0x00007FF6D78A61EA]\n\t(No symbol) [0x00007FF6D7888E03]\n\t(No symbol) [0x00007FF6D785D686]\n\t(No symbol) [0x00007FF6D785CB92]\n\t(No symbol) [0x00007FF6D785D4B3]\n\t(No symbol) [0x00007FF6D795900D]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D7966943+41539]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D795FC79+13689]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6D7BDA04A+290794]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A57D31+497697]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50BB4+468644]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50D03+468979]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A42E16+411910]\n\tBaseThreadInitThunk [0x00007FF800A5259D+29]\n\tRtlUserThreadStart [0x00007FF80186AF38+40]\n'
Arguments: ()

2025-04-29 16:33:18,195 - DEBUG - Subprocess returncode: 0
2025-04-29 16:33:18,216 - INFO - Retained file for resume: D:\Internship\automation\automation\uploads\lkp23.xlsx
2025-04-29 16:33:18,216 - WARNING - Process failed at row 3: Terdeteksi berhenti pada baris 3
2025-04-29 16:34:35,891 - DEBUG - Subprocess stdout: {"status": "error", "message": "Terdeteksi berhenti pada baris 3", "last_row": 3}

2025-04-29 16:34:35,891 - DEBUG - Subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23_aQu3B9l.xlsx']
File 1 found: D:\Internship\automation\automation\uploads\lkp23_aQu3B9l.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 35, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 46, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 71, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 90, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp23_aQu3B9l.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 2 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 151, in process_files
    driver.execute_script("arguments[0].click();", link_tambah_siswa)
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 528, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Acer\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: MicrosoftEdge=135.0.3179.98)
Stacktrace:
	GetHandleVerifier [0x00007FF6D7AF7A55+24981]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A4AC60+444240]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6D7D7E0EA+2011274]
	(No symbol) [0x00007FF6D780B880]
	(No symbol) [0x00007FF6D782A24A]
	(No symbol) [0x00007FF6D788ED66]
	(No symbol) [0x00007FF6D78A61EA]
	(No symbol) [0x00007FF6D7888E03]
	(No symbol) [0x00007FF6D785D686]
	(No symbol) [0x00007FF6D785CB92]
	(No symbol) [0x00007FF6D785D4B3]
	(No symbol) [0x00007FF6D795900D]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D7966943+41539]
	Microsoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D795FC79+13689]
	Microsoft::Applications::Events::EventProperty::to_string [0x00007FF6D7BDA04A+290794]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A57D31+497697]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50BB4+468644]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50D03+468979]
	Microsoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A42E16+411910]
	BaseThreadInitThunk [0x00007FF800A5259D+29]
	RtlUserThreadStart [0x00007FF80186AF38+40]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 34: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 203, in process_files
    logging.error(f"\u274c Browser ditutup pada baris {i}: {e}")
Message: '\u274c Browser ditutup pada baris 3: Message: invalid session id: session deleted as the browser has closed the connection\nfrom disconnected: not connected to DevTools\n  (Session info: MicrosoftEdge=135.0.3179.98)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D7AF7A55+24981]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A4AC60+444240]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6D7D7E0EA+2011274]\n\t(No symbol) [0x00007FF6D780B880]\n\t(No symbol) [0x00007FF6D782A24A]\n\t(No symbol) [0x00007FF6D788ED66]\n\t(No symbol) [0x00007FF6D78A61EA]\n\t(No symbol) [0x00007FF6D7888E03]\n\t(No symbol) [0x00007FF6D785D686]\n\t(No symbol) [0x00007FF6D785CB92]\n\t(No symbol) [0x00007FF6D785D4B3]\n\t(No symbol) [0x00007FF6D795900D]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D7966943+41539]\n\tMicrosoft::Applications::Events::EventProperty::~EventProperty [0x00007FF6D795FC79+13689]\n\tMicrosoft::Applications::Events::EventProperty::to_string [0x00007FF6D7BDA04A+290794]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A57D31+497697]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50BB4+468644]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A50D03+468979]\n\tMicrosoft::Applications::Events::ILogConfiguration::operator* [0x00007FF6D7A42E16+411910]\n\tBaseThreadInitThunk [0x00007FF800A5259D+29]\n\tRtlUserThreadStart [0x00007FF80186AF38+40]\n'
Arguments: ()

2025-04-29 16:34:35,891 - DEBUG - Subprocess returncode: 0
2025-04-29 16:34:35,919 - INFO - Retained file for resume: D:\Internship\automation\automation\uploads\lkp23_aQu3B9l.xlsx
2025-04-29 16:34:35,919 - WARNING - Process failed at row 3: Terdeteksi berhenti pada baris 3
2025-04-29 16:36:33,222 - DEBUG - Resume subprocess stdout: {"status": "success", "message": "Semua 1 file berhasil diproses!", "last_row": 13}

2025-04-29 16:36:33,222 - DEBUG - Resume subprocess stderr: === DEBUG INFO ===
Current directory: D:\Internship\automation\automation\automation
Script location: D:\Internship\automation\automation\automation\otomatisasi.py
Args received: ['D:\\Internship\\automation\\automation\\automation\\otomatisasi.py', 'D:\\Internship\\automation\\automation\\uploads\\lkp23_aQu3B9l.xlsx', '--resume-from', '3']
File 1 found: D:\Internship\automation\automation\uploads\lkp23_aQu3B9l.xlsx
=================
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 35, in process_files
    logging.info("\u2705 Silakan login di browser... Menunggu hingga login selesai...")
Message: '\u2705 Silakan login di browser... Menunggu hingga login selesai...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 46, in process_files
    logging.info("\u2705 Login terdeteksi! Melanjutkan otomatisasi...")
Message: '\u2705 Login terdeteksi! Melanjutkan otomatisasi...'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 71, in process_files
    logging.info("\u2705 Berhasil klik link 'Daftar Siswa Aktif'")
Message: "\u2705 Berhasil klik link 'Daftar Siswa Aktif'"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f535' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 90, in process_files
    logging.info(f"\U0001f535 Memulai proses file: {file_path}")
Message: '\U0001f535 Memulai proses file: D:\\Internship\\automation\\automation\\uploads\\lkp23_aQu3B9l.xlsx'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 3 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 4 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 5 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 6 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 7 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 8 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 9 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 10 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 11 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 201, in process_files
    logging.info(f"\u2705 Baris {i} berhasil diproses")
Message: '\u2705 Baris 12 berhasil diproses'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 220, in process_files
    logging.info(f"\u2705 File {file_path} berhasil diproses!")
Message: '\u2705 File D:\\Internship\\automation\\automation\\uploads\\lkp23_aQu3B9l.xlsx berhasil diproses!'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2705' in position 33: character maps to <undefined>
Call stack:
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 282, in <module>
    result = process_files(args.file_paths, resume_from=args.resume_from)
  File "D:\Internship\automation\automation\automation\otomatisasi.py", line 233, in process_files
    logging.info("\u2705 Semua file telah diproses!")
Message: '\u2705 Semua file telah diproses!'
Arguments: ()

2025-04-29 16:36:33,236 - DEBUG - Resume subprocess returncode: 0
2025-04-29 16:36:33,239 - INFO - File deleted after successful resume: D:\Internship\automation\automation\uploads\lkp23_aQu3B9l.xlsx
2025-04-29 16:36:33,239 - INFO - Successfully resumed processing for log ID 27
